emails_autorizados:
- fcltenciano@gmail.com
- francistenciano@gmail.com
- renatinhobsb@gmail.com
- lucasfernando.cp@hotmail.com
- alvaro.kaires@gmail.com
- ricardo.pereira.bahia@gmail.com
- sandropatto@hotmail.com 
- sadaohatore@gmail.com
- carloshachtrader@gmail.com
- rwescritorio@gmail.com
- thediogosales@gmail.com
- mcp.prof.prod2@gmail.com
- williamfiais@outlook.com
- leandro8x@gmail.com 
- marcelacampos33333@gmail.com
- mikeserafim@gmail.com
- paulomarinhommm@gmail.com
- natocosta@gmail.com
- fsilva1604@gmail.com 
- gwilltj@gmail.com
- jcdcsrock@gmail.com
- enrico.viana@gmail.com
- marciotraderstar@gmail.com
