emails_autorizados:
- fcltenciano@gmail.com
- francistenciano@gmail.com
- renatinhobsb@gmail.com
- lucasfernando.cp@hotmail.com
- alvaro.kaires@gmail.com
- ricardo.pereira.bahia@gmail.com
- sandropatto@hotmail.com 
- sadaohatore@gmail.com
- 
